name: Idea / Enhancement
description: Share an idea
title: "[Idea]: "
labels: ["idea", "enhancement"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your idea / enhancement
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: justificiation
    attributes:
      label: How would this be beneficial?
    validations:
      required: true